---
- name: Install node and npm
  hosts: aws
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
        # could be written like this
        # update_cache: yes 
    - name: Install nodejs and npm
      apt: 
        pkg:
          - nodejs
          - npm
### part 3 ###
- name: Create new linux user for node app
  hosts: aws
  tasks:
    - name: Createe linux user
      user: 
        name: hossam
        comment: Hossam Admin
        group: admin
###############
- name: Deploy nodejs app
  hosts: aws
  become: True # enable changing user
  become_user: hossam # default is root
  tasks:
    - name: Unpack the nodejs tar file
      unarchive:
        src: nodejs-app-1.0.0.tgz
        dest: /home/hossam
    #### part 2 ####
    - name: Install dependencies
      npm:
        path: /home/hossam/package
    - name: Start the application
      command:
        chdir: /home/hossam/package/app
        cmd: node server
      # run the command in background
      async: 1000  
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node # command is more secure
      register: app_status # save result in a variable
    - debug: msg={{app_status.stdout_lines}}





    
