---
- name: Install node and npm
  hosts: aws
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
        # could be written like this
        # update_cache: yes 
    - name: Install nodejs and npm
      apt: 
        pkg:
          - nodejs
          - npm
### part 3 ###
- name: Create new linux user for node app
  hosts: aws
  vars_files: 
    - project-vars
  tasks:
    - name: Createe linux user
      user: 
        name: "{{linux_name}}"
        comment: "{{linux_name}} Admin"
        group: admin
      register: user_creation_result
    - debug: msg={{user_creation_result}}
###############
- name: Deploy nodejs app
  hosts: aws
  become: True # enable changing user
  become_user: "{{linux_name}}" # default is root
  vars_files: 
    - project-vars # location of file
  vars: 
  #  - location: "."
  #  - version: 1.0.0
  #  - destination: /home/{{linux_name}}
  tasks:
    - name: Unpack the nodejs tar file
      unarchive:
        src: "{{location}}/nodejs-app-{{version}}.tgz"
        dest: "{{destination}}"
      register: unpack_tar
    - debug: msg={{unpack_tar}}
    #### part 2 ####
    - name: Install dependencies
      npm:
        path: "{{destination}}/package"
    - name: Start the application
      command:
        chdir: "{{destination}}/package/app"
        cmd: node server
      # run the command in background
      async: 1000  
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node # command is more secure
      register: app_status # save result in a variable
    - debug: msg={{app_status.stdout_lines}}





    
