---
- name: Configure nginx web server
  hosts: aws
  become: yes
  tasks:
  # for an ubuntu server
  - name: install nginx server
    apt: 
      name: nginx
      state: latest # absent to uninstall 
      to install a specific version
      name: nginx=1.18.0-0ubuntu1
      state: present
      
  - name: start nginx server
    service:
      name: nginx
      state: started #stopped